<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 2017/9/13
 * Time: 15:27
 */

namespace backend\controllers;


use yii\web\Controller;
use Yii;
class MainController extends Controller{
    //模板数据
    public $renderData = [];
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
   }

   //调用模板，加载layout
   public function display($view = ''){
       $view = $view ? $view : '/' . $this->id . '/'. $this->action->id;
       return $this->render($view, $this->renderData);
   }

   //调用模板， 不加载layout
   public function displayPartial($view = ''){
       $view = $view ? $view : '/' . $this->id . '/'. $this->action->id;
       return $this->renderPartial($view, $this->renderData);
   }
}