<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 2017/6/5
 * Time: 19:46
 */
namespace backend\models;
use yii\base\Model;
use yii\web\UploadedFile;

class SettingForm extends Model{
    //站点名
    public $sitename;
    //站点描述
    public $desctiption;
    //站点关键字
    public $keyword;
    //热线电话
    public $footinfo;

    public $id;

    public $app_id;

    public $app_sec;

    public function rules() {
        return [
            [
                ['sitename', 'desctiption', 'keyword', 'footinfo', 'app_id', 'app_sec'], 'trim'
            ],
        ];
    }

    public function attributeLabels() {
        return [
            'sitename' => '站点名',
            'desctiption' => '站点描述',
            'keyword' => '站点关键字',
            'footinfo' => '底部信息',
            'app_id' => '公众号APPID',
            'app_sec' => '公众号APPSEC',

        ]; // TODO: Change the autogenerated stub
    }

}